org: superdoug
app: serverlesstemplate
service: #!update!#

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
functions:
  #!update!#:
  handler: src/functions/ #!update!#.#!update!#
  events:
    - http:
        method: #!update!#
        cors: true
        path: /v1/ #!update!#
        authorizer:
          arn: arn:aws:lambda:us-east-1:789699194703:function:authorization-dev-auth
          type: token

plugins:
  - serverless-mocha
custom:
  serverless-mocha-plugin:
    testTemplate: templates/test-template.ejs
    functionTemplate: templates/function-template.ejs

package:
  patterns:
    - "!package-lock.json"
    - "!templates/**"
    - "!README.md"
    # may want to remove test files - tbd
